/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardDetailedRouteImport } from './routes/dashboard.detailed'
import { Route as DashboardOtherRouteImport } from './routes/dashboard.other'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as ApiUsersUserIdHistoryDotcsvRouteImport } from './routes/api/users/$userId/history[.]csv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetailedRoute = DashboardDetailedRouteImport.update({
  id: '/detailed',
  path: '/detailed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOtherRoute = DashboardOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUsersUserIdHistoryDotcsvRoute =
  ApiUsersUserIdHistoryDotcsvRouteImport.update({
    id: '/api/users/$userId/history.csv',
    path: '/api/users/$userId/history.csv',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/detailed': typeof DashboardDetailedRoute
  '/dashboard/other': typeof DashboardOtherRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/users/$userId/history.csv': typeof ApiUsersUserIdHistoryDotcsvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/detailed': typeof DashboardDetailedRoute
  '/dashboard/other': typeof DashboardOtherRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/users/$userId/history.csv': typeof ApiUsersUserIdHistoryDotcsvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/detailed': typeof DashboardDetailedRoute
  '/dashboard/other': typeof DashboardOtherRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/users/$userId/history.csv': typeof ApiUsersUserIdHistoryDotcsvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/dashboard/analytics'
    | '/dashboard/detailed'
    | '/dashboard/other'
    | '/dashboard/referrals'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/users/$userId/history.csv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/dashboard/analytics'
    | '/dashboard/detailed'
    | '/dashboard/other'
    | '/dashboard/referrals'
    | '/dashboard/users'
    | '/dashboard'
    | '/api/users/$userId/history.csv'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/dashboard/analytics'
    | '/dashboard/detailed'
    | '/dashboard/other'
    | '/dashboard/referrals'
    | '/dashboard/users'
    | '/dashboard/'
    | '/api/users/$userId/history.csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUsersUserIdHistoryDotcsvRoute: typeof ApiUsersUserIdHistoryDotcsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detailed': {
      id: '/dashboard/detailed'
      path: '/detailed'
      fullPath: '/dashboard/detailed'
      preLoaderRoute: typeof DashboardDetailedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/other': {
      id: '/dashboard/other'
      path: '/other'
      fullPath: '/dashboard/other'
      preLoaderRoute: typeof DashboardOtherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/users/$userId/history.csv': {
      id: '/api/users/$userId/history.csv'
      path: '/api/users/$userId/history.csv'
      fullPath: '/api/users/$userId/history.csv'
      preLoaderRoute: typeof ApiUsersUserIdHistoryDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDetailedRoute: typeof DashboardDetailedRoute
  DashboardOtherRoute: typeof DashboardOtherRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDetailedRoute: DashboardDetailedRoute,
  DashboardOtherRoute: DashboardOtherRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiUsersUserIdHistoryDotcsvRoute: ApiUsersUserIdHistoryDotcsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
